version: '3'

services:

  user-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - user-db:/var/lib/mysql

  spring-user-app:
    image: user-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_IP: user-db
      DB_PORT: 3306
      DB_DBNAME: user_db
    ports:
      - "8080:8080"
    depends_on:
      - user-db

volumes:
  user-db:

